apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-legacy
  labels:
    app: webgoat-legacy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webgoat-legacy
  template:
    metadata:
      labels:
        app: webgoat-legacy
    spec:
      containers:
      - name: webgoat-legacy
        image: <your-acr-name>.azurecr.io/webgoat-legacy:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat-legacy-service
spec:
  selector:
    app: webgoat-legacy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer