// Removed unused methods and dead code from the class.
// ...existing code...
// Removed unused method: private void unusedHelperMethod() {...}
// Removed dead code: if (false) {...}
// ...existing code...